server:
  port: 8089
  servlet:
    context-path: /shop
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shopping?characterEncoding=utf8
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.zretc.pojo
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.zretc.pojo
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info
    com.zretc: debug
    org.springframework.web: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql